version: "3.7"
services:
  app:
    container_name: app
    build:
      context: .
      args:
        NODE_VERSION: ${NODE_VERSION}
      target: ${APP_ENV}
    restart: on-failure
    ports:
      - "${PORT}:4000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    env_file:
      - .env
  mongo:
    container_name: mongo
    image: mongo:${MONGO_VERSION}
    restart: on-failure
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ./src/db:/data/db
